// VEHICLE
export const ADMIN_ADD_VEHICLE_SUCCESS = 'ADMIN_ADD_VEHICLE_SUCCESS';
export const ADMIN_ADD_VEHICLE_FAILED = 'ADMIN_ADD_VEHICLE_FAILED';
export const ADMIN_UPDATE_VEHICLE_SUCCESS = 'ADMIN_UPDATE_VEHICLE_SUCCESS';
export const ADMIN_UPDATE_VEHICLE_FAILED = 'ADMIN_UPDATE_VEHICLE_FAILED';
export const ADMIN_DELETE_VEHICLE_SUCCESS = 'ADMIN_DELETE_VEHICLE_SUCCESS';
export const ADMIN_DELETE_VEHICLE_FAILED = 'ADMIN_DELETE_VEHICLE_FAILED';
export const ADMIN_GET_ALL_VEHICLES_SUCESS = 'ADMIN_GET_ALL_VEHICLES_SUCESS';
export const ADMIN_GET_ALL_VEHICLES_FAILED = 'ADMIN_GET_ALL_VEHICLES_FAILED';
export const ADMIN_GET_VEHICLE_BY_ID_SUCCESS =
  'ADMIN_GET_VEHICLE_BY_ID_SUCCESS';
export const ADMIN_GET_VEHICLE_BY_ID_FAILED = 'ADMIN_GET_VEHICLE_BY_ID_FAILED';
